### ISSUE TITLE
Tasklist do mega projeto

### ISSUE THREAD

**Issue by chicodias** [chicodias/ipeadatar-shiny#2]
# Frente 1: Análise de dados

## Tarefinha da vez:
- Escolha uma das séries na lista abaixo e realize as tarefas da parte 0 (Análise Exploratória). 
- Pode ser em python ou R.
- Vamos incluir **os notebooks** das análises realizadas nesta etapa dentro de nosso portal na sessão "Análises"

Abaixo, estão os indicadores mais importantes para a economia brasileira. Que tal escolher uma dessas séries e colocar seu nome? :thinking: 

###  FGV:
  - IGP-M 
  - INCC
  - IPC
###  Bacen
  - CDI
  - Selic
  - TR
###  IBGE
  - IPCA
  - INPC
  - PIB

Todas elas estão disponíveis em nosso painel. (Mantenha o código da série fácil de encontrar tbm!)

# Tarefas
  0. Análise exploratória
     - Dados faltantes,
     - Autocorrelação,
     - Sazonalidade,
     - Tendência,
     - Transformações que "melhorem" a cara dos dados,
     - Encontrar séries correlacionadas,
     - Gráficos variados.
  1. Modelagem
  2. Diagnóstico
  3. Previsão
  
Sugestões de gráficos:
 - Time plot
 - Seasonal plot
 - Subseries plot
 - Lag plot
 - Ruído

# Frente 2: Redação do relatório:

[Link do Overleaf](https://www.overleaf.com/6425865967gmhqbnvnrgjyl)

No relatório, por enquanto não precisamos focar tanto em escrever. Mas uma ajuda extra na revisão de citação e referências é sempre bem vinda :cowboy_hat_face: 

 1. Introdução 
 2. Sobre os dados
 3. Sobre o que desejamos saber
 4. Sobre a Teoria
 5. Sobre a plataforma

**Comment by Eeeeeenzoooo** [comment]
> # Frente 1: Análise de dados
> ## Tarefinha da vez:
> * Escolha uma das séries na lista abaixo e realize as tarefas da parte 0 (Análise Exploratória).
> * Pode ser em python ou R.
> * Vamos incluir **os notebooks** das análises realizadas nesta etapa dentro de nosso portal na sessão "Análises"
> 
> Abaixo, estão os indicadores mais importantes para a economia brasileira. Que tal escolher uma dessas séries e colocar seu nome? 🤔
> 
> ### FGV:
> * IGP-M
> * INCC (enzuuu)
> * IPC
> 
> ### Bacen
> * CDI
> * Selic
> * TR
> 
> ### IBGE
> * IPCA
> * INPC
> * PIB 
> 
> Todas elas estão disponíveis em nosso painel. (Mantenha o código da série fácil de encontrar tbm!)
> 
> # Tarefas
> 0. Análise exploratória
>    
>    * Dados faltantes,
>    * Autocorrelação,
>    * Sazonalidade,
>    * Tendência,
>    * Transformações que "melhorem" a cara dos dados,
>    * Encontrar séries correlacionadas,
>    * Gráficos variados.
> 1. Modelagem
> 2. Diagnóstico
> 3. Previsão
> 
> Sugestões de gráficos:
> 
> * Time plot
> * Seasonal plot
> * Subseries plot
> * Lag plot
> * Ruído
> 
> # Frente 2: Redação do relatório:
> [Link do Overleaf](https://www.overleaf.com/6425865967gmhqbnvnrgjyl)
> 
> No relatório, por enquanto não precisamos focar tanto em escrever. Mas uma ajuda extra na revisão de citação e referências é sempre bem vinda 🤠
> 
> 1. Introdução
> 2. Sobre os dados
> 3. Sobre o que desejamos saber
> 4. Sobre a Teoria
> 5. Sobre a plataforma
