### ISSUE TITLE
Pré processamento das séries

### ISSUE THREAD

**Issue by chicodias** [chicodias/ipeadatar-shiny#6]
Algumas coisas pra fazer:

## UI
- [x] Frontend: arrumar o tema [Referencia](https://shiny.posit.co/r/getstarted/build-an-app/customizing-ui/theming.html)
- [x] Colocar os gráficos em tabs separadas. [Referencia](https://shiny.posit.co/r/getstarted/build-an-app/customizing-ui/tabs.html) Podia ter tabs como:
    - Decomposição
    - Correlograma
    - Sazonal: talvez incluir mais algum parâmetro no input aqui? [Referencia](https://feasts.tidyverts.org/reference/gg_season.html)
    - Subséries
    - Lag plot

## Decomposições
Aqui basta incluir [mais casos na lógica do backend](https://github.com/chicodias/ipeadatar-shiny/blob/58cf65f60dd116d3c5a5c9891fbd29d1dfa4d2c7/shiny/server.R#L132), e depois habilitar as opções no [frontend](https://github.com/chicodias/ipeadatar-shiny/blob/58cf65f60dd116d3c5a5c9891fbd29d1dfa4d2c7/shiny/ui.R#L45)
- [x] STL: Incluir janela de tendência como input. [Referencia](https://otexts.com/fpp3/stl.html)
- [x] Clássica: Adicionar decomposição clássica [Referencia](https://otexts.com/fpp3/classical-decomposition.html)
- [x] X11, SEATS: Adicionar decomposições mais chiques de bonus [Referencia](https://otexts.com/fpp3/methods-used-by-official-statistics-agencies.html)

## Transformações
- [x] Delimitar os dados de acordo com `input$date` (ainda não tenho certeza de como fazer isso)

**Comment by augusnunes** [comment]
#7 inclui as decomposições faltantes

**Comment by chicodias** [comment]
Boa!!! Rolou tudo aqui, agora só falta a ultima parte de previsão :pray:
